//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_PhongThuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int transaction_id { get; set; }
        public int qty { get; set; }
        public string Name;
        public decimal Price;
        public decimal tong_price;
        public virtual SanPham SanPham { get; set; }
    }
}
