//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_PhongThuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string user_mail { get; set; }
        public string user_phone { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string Code { get; set; }
        public string DeliveryPaymentMethod { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string ghi_chu { get; set; }
    }
}
