//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_PhongThuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        public int id { get; set; }
        public string name { get; set; }
        public string id_loaisp { get; set; }
    }
}
