//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G7_PhongThuyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public string image_link { get; set; }
        public string author { get; set; }
        public System.DateTime created { get; set; }
    }
}
